SELECT
    YEAR(t.DIFFERENTIATION_DATE) AS YEAR,
    (m.max_size - t.SIZE_OF_COLONY) AS YEAR_DEV,
    t.ID
FROM
    ECOLI_DATA t
JOIN (
        SELECT
            YEAR(DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS max_size
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) m ON YEAR(t.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY YEAR, YEAR_DEV;
